package com.chamchamcham.application.exception

enum class ErrorCode(
    val code: String,
    val messageKey: String,
    val status: Int
) {

    INVALID_INPUT("COMMON_001", "error.invalid_input", 400),
    INVALID_JSON("COMMON_002", "error.invalid_json", 400),
    INVALID_CURSOR("COMMON_003", "error.invalid_cursor", 400),
    INTERNAL_ERROR("COMMON_999", "error.internal_error", 500),
    RESOURCE_NOT_FOUND("RESOURCE_001","error.resource_not_found", 404),
    MEMBER_NOT_FOUND("MEMBER_001", "error.member_not_found", 404),
    CROP_NOT_FOUND("CROP_001", "error.crop_not_found", 404),
    FARM_NOT_FOUND("FARM_001", "error.farm_not_found", 404),
    MEDIA_NOT_FOUND("MEDIA_001", "error.media_not_found", 404),
    MEDIA_NOT_OWNED("MEDIA_002", "error.media_not_owned", 403),
    MEDIA_USAGE_MISMATCH("MEDIA_003", "error.media_usage_mismatch", 400),
    MEDIA_NOT_ATTACHABLE("MEDIA_004", "error.media_not_attachable", 400),
    MEDIA_TOO_LARGE("MEDIA_005", "error.media_too_large", 400),
    MEDIA_UPLOAD_FAILED("MEDIA_006", "error.media_upload_failed", 503),
    COMMUNITY_POST_NOT_FOUND("COMMUNITY_001", "error.community_post_not_found", 404),
    COMMUNITY_COMMENT_NOT_FOUND("COMMUNITY_002", "error.community_comment_not_found", 404),
    COMMUNITY_FORBIDDEN("COMMUNITY_003", "error.community_forbidden", 403),
    COMMUNITY_INVALID_REPLY_PARENT("COMMUNITY_004", "error.community_invalid_reply_parent", 400),
    COMMUNITY_TOO_MANY_IMAGES("COMMUNITY_005", "error.community_too_many_images", 400),
    COMMUNITY_FARMING_RECORD_CROP_MISMATCH("COMMUNITY_006", "error.community_farming_record_crop_mismatch", 400),
    FARMING_RECORD_NOT_FOUND("FARMING_001", "error.farming_record_not_found", 404),
    FARMING_RECORD_DETAIL_REQUIRED("FARMING_002", "error.farming_record_detail_required", 400),
    FARMING_RECORD_INVALID_DETAIL("FARMING_003", "error.farming_record_invalid_detail", 400),
    USER_ALREADY_EXISTS("USER_002", "error.user_already_exists", 409),
    DUPLICATE_EMAIL("AUTH_003", "error.duplicate_email", 409),
    EMAIL_NOT_VERIFIED("AUTH_004", "error.email_not_verified", 400),
    AUTH_CODE_NOT_FOUND("AUTH_005", "error.auth_code_not_found", 404),
    AUTH_CODE_MISMATCH("AUTH_006", "error.auth_code_mismatch", 400),
    ALREADY_LOGGED_OUT("AUTH_007", "error.already_logged_out", 400),
    MALFORMED_JWT("AUTH_008", "error.malformed_jwt", 400),
    INVALID_KAKAO_TOKEN("AUTH_009", "error.invalid_kakao_token", 401),
    KAKAO_NONCE_MISMATCH("AUTH_010", "error.kakao_nonce_mismatch", 401),
    KAKAO_NONCE_REPLAY("AUTH_011", "error.kakao_nonce_replay", 401),
    KAKAO_VERIFIED_EMAIL_REQUIRED("AUTH_012", "error.kakao_verified_email_required", 422),
    SOCIAL_ONLY_MEMBER_LOCAL_LOGIN_FORBIDDEN("AUTH_013", "error.social_only_member_local_login_forbidden", 400),
    KAKAO_OIDC_UNAVAILABLE("AUTH_014", "error.kakao_oidc_unavailable", 503),
    INVALID_APPLE_TOKEN("AUTH_015", "error.invalid_apple_token", 401),
    APPLE_NONCE_MISMATCH("AUTH_016", "error.apple_nonce_mismatch", 401),
    APPLE_NONCE_REPLAY("AUTH_017", "error.apple_nonce_replay", 401),
    APPLE_VERIFIED_EMAIL_REQUIRED("AUTH_018", "error.apple_verified_email_required", 422),
    INVALID_NAVER_TOKEN("AUTH_019", "error.invalid_naver_token", 401),
    NAVER_PROFILE_UNAVAILABLE("AUTH_020", "error.naver_profile_unavailable", 503),
    NAVER_EMAIL_REQUIRED("AUTH_021", "error.naver_email_required", 422),
    UNAUTHORIZED("AUTH_001", "error.unauthorized", 401),
    FORBIDDEN("AUTH_002", "error.forbidden", 403),

}
